services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/app:/app/app
      - ./dockerdata/dev/backend/data:/app/data
      - ./dockerdata/dev/backend/logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - LOG_FILE_PATH=/app/logs/server.log
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    volumes:
      - ./dockerdata/dev/frontend/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - backend
    environment:
      - VITE_OTEL_COLLECTOR_URL=http://otel-collector:4318/v1/traces
      - VITE_OTEL_COLLECTOR_METRICS_URL=http://otel-collector:4318/v1/metrics
      - VITE_OTEL_COLLECTOR_LOGS_URL=http://otel-collector:4318/v1/logs
      - VITE_OTEL_METRICS_ENABLED=true
      - VITE_SERVICE_NAME=frontend-app
