services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
