version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.90.1
    command: [ --config=/etc/otel-collector-config.yml ]
    volumes:
      - ./dockerdata/observability/otel-collector/collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "8889:8889" # Prometheus metrics exporter
    depends_on:
      - prometheus
      - tempo
      - loki
      - jaeger

  prometheus:
    image: prom/prometheus:v2.48.0
    volumes:
      - ./dockerdata/observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./dockerdata/observability/prometheus/data:/prometheus:Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.2.2
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dockerdata/observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./dockerdata/observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  loki:
    image: grafana/loki:2.9.2
    command: -config.file=/etc/loki/local-config.yml
    user: "0" # Important for Podman compatibility
    volumes:
      - ./dockerdata/observability/loki/loki-config.yml:/etc/loki/local-config.yml
      - ./dockerdata/observability/loki/data:/tmp/loki:Z # For data persistence, preferred over named volume
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:2.2.2
    command: -config.file=/etc/tempo/tempo.yml
    volumes:
      - ./dockerdata/observability/tempo/tempo-config.yml:/etc/tempo/tempo.yml
      - ./dockerdata/observability/tempo/data:/tmp/tempo
    ports:
      - "14268:14268" # Jaeger gRPC
      - "14250:14250" # Jaeger Thrift
      - "3200:3200" # Tempo UI/HTTP
      - "9411:9411" # Zipkin

  test-sender:
    image: alpine/curl
    volumes:
      - ./dockerdata/observability/otel-collector/test-sender.sh:/usr/local/bin/test-sender.sh
    command: >
      sh -c "
        chmod +x /usr/local/bin/test-sender.sh &&
        /usr/local/bin/test-sender.sh
      "
    depends_on:
      - otel-collector

volumes:

