services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/app:/app/app
      - ./dockerdata/prod/backend/data:/app/data
      - ./dockerdata/prod/backend/logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - LOG_FILE_PATH=/app/logs/server.log
      - APP_ENV=prod

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    volumes:
      - ./dockerdata/prod/frontend/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - backend
