[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "alembic>=1.18.5",
    "bcrypt>=5.0.0",
    "fastapi>=0.140.0",
    "httpx>=0.28.1",
    "passlib[bcrypt]>=1.7.4",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "python-jose>=3.5.0",
    "python-json-logger>=4.1.0",
    "sqlalchemy>=2.0.51",
    "uvicorn>=0.51.0",
    "opentelemetry-api>=1.15.0",
    "opentelemetry-sdk>=1.15.0",
    "opentelemetry-sdk",
    "opentelemetry-exporter-otlp",
    "opentelemetry-instrumentation-fastapi",
    "opentelemetry-instrumentation-httpx",
    "opentelemetry-instrumentation-logging",
    "opentelemetry-instrumentation-sqlalchemy",
    "opentelemetry-instrumentation-system-metrics",
    "opentelemetry-exporter-prometheus",
    "opentelemetry-sdk-extension-aws",
    "prometheus-fastapi-instrumentator",
    "chromadb>=0.6.3",
    "sentence-transformers>=5.0.0",
    "mlflow>=2.22.0",
    "langchain-core>=0.2.19",
    "langchain-community>=0.2.19",
    "langchain>=0.2.0",
    "langchain-text-splitters>=0.3.0",
    "pypdf>=5.0.0",
]

