{
 "title": "Nginx Observability",
 "tags": [
  "nginx",
  "observability"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Accepted Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_connections_accepted_total)",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(nginx_connections_active)", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Handled Connections Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_handled_total[1m]))",
     "legendFormat": "Handled/sec"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[1m]))",
     "legendFormat": "Requests/sec"
    }
   ]
  },
  {
   "title": "Connections / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_accepted_total[1m]))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(rate(nginx_connections_handled_total[1m]))",
     "legendFormat": "Handled"
    }
   ]
  }
 ]
}