"""create_trace_configurations_table

Revision ID: f2a7b8c9d0e1
Revises: 5c5a3b15fd7e
Create Date: 2026-07-30 21:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a7b8c9d0e1'
down_revision: Union[str, Sequence[str], None] = '5c5a3b15fd7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trace_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True, default=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trace_configurations_id'), 'trace_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_trace_configurations_service_name'), 'trace_configurations', ['service_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trace_configurations_service_name'), table_name='trace_configurations')
    op.drop_index(op.f('ix_trace_configurations_id'), table_name='trace_configurations')
    op.drop_table('trace_configurations')
    # ### end Alembic commands ###
