server:
  http_listen_port: 3200

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces

compactor:
  compaction:
    block_retention: 168h

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http: