server:
  http_listen_port: 3200

metrics:
  wal_path: /tmp/tempo/wal

storage:
  trace:
    backend: local
    filepath: /tmp/tempo/traces

compactor:
  compaction:
    compacted_blocks_retention: 1h
    block_retention: 1h

querier:
  max_query_parallelism: 200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http: